---
title: "Base de Dados - Dissertação"
output: html_document
author: Renato Victor Lira Brito
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
```

```{r}
library(poliscidata)

library(tidyverse)
```

```{r}
PAÍS <- c("Estados Unidos da América", "Canadá", "Uruguai", 
          "México", "Paraguai", "Brasil", "Colômbia", "Cuba", 
          "Chile", "República Dominicana", "Jamaica", "Argentina", 
          "Peru", "Panamá", "Equador", "Venezuela", "Guatemala", 
          "Antígua e Barbuda", "Costa Rica", "Trindade e Tobago", "Barbados", "São Vicente e Granadinas", "Bahamas", "Granada", "Bolívia", "Guiana", "Nicarágua", "Belize", "El Salvador", "Suriname", "Santa Lúcia", "São Cristóvão e Névis", "Haiti", "Honduras", "Dominica")

SIGLA <- c("EUA", "CAN", "URU", "MEX", "PAR", "BRA", "COL", "CUB", "CHI", "DOM", "JAM", "ARG", "PER", "PAN", "ECU", "VEN", "GUA", "ANT", "CRC", "TRI", "BAR", "VIN", "BAH", "GRN", "BOL", "GUY", "NCA", "BIZ", "ESA", "SUR", "LCA", "SKN", "HAI", "HON", "DMA")

RANQUE_REGIONAL <- c(1, 2, 3, 4, 5, 
                     6, 7, 8, 9, 10, 
                     11, 11, 12, 13,
                     14, 15, 16, 17, 
                     18, 19, 20, 21, 
                     22, 23, 24, 25, 
                     26, 26, 27, 28,
                     29, 30, 31, 32,
                     33)

RANQUE_GLOBAL <- c(2, 9, 51, 63, 66, 70, 73, 81, 83, 92, 94, 94, 95, 97, 98, 99, 112, 113, 115, 123, 127, 129, 133, 134, 135, 138, 140, 140, 142, 144, 149, 157, 164, 165, 172)

PONTUAÇÃO_GCI <- c(0.926, 0.892, 0.681, 0.629, 
                   0.603, 0.577, 0.565, 0.481,
                   0.470, 0.430, 0.407, 0.407, 
                   0.401, 0.369, 0.367, 0.354, 
                   0.251, 0.247, 0.221, 0.188, 
                   0.173, 0.169, 0.147, 0.143, 
                   0.139, 0.132, 0.129, 0.129, 
                   0.124, 0.110, 0.096, 0.065, 
                   0.046, 0.044, 0.019)

PONTUAÇÃO_GCI_TRATADO <- c(1, 1, 1, 1, 1, 
                           1, 1, 1, 1, 0, 
                           0, 0, 0, 0, 0, 
                           0, 0, 0, 0, 0, 
                           0, 0, 0, 0, 0, 
                           0, 0, 0, 0, 0, 
                           0, 0, 0, 0, 0)

PONTUAÇÃO_IDH <- c(0.920, 0.922, 0.808, 0.767, 0.724, 
                   0.761, 0.761, 0.778, 0.847, 0.745, 
                   
                   0.726, 0.830, 0.759, 0.795, 0.758, 
                   0.726, 0.651, 0.776, 0.794, 0.799, 
                   
                   0.813, 0.728, 0.805, 0.763, 0.703, 
                   0.670, 0.651, 0.720, 0.667, 0.724, 
                   0.745, 0.777, 0.503, 0.623, 0.724)

PONTUAÇÃO_IDH_TRATADO <- c(2, 2, 2, 1, 1, 
                           1, 1, 1, 2, 1, 
                           1, 2, 1, 1, 1,
                           1, 0, 1, 1, 1,
                           2, 1, 2, 2, 1,
                           0, 0, 1, 0, 1,
                           1, 1, 0, 0, 1)

PONTUAÇÃO_MILITARIZAÇÃO_TRATADO <- c(0, 0, 0, 0, 0,
                                     1, 1, 0, 0, 0,
                                     0, 0, 0, 0, 0,
                                     0, 0, 0, 0, 0,
                                     0, 0, 0, 0, 0,
                                     0, 0, 0, 0, 0,
                                     0, 0, 0, 0, 0)

PONTUAÇÃO_EVENTOS_RAROS_TRATADO <- c(3, 3, 1, 1, 1,
                                     2, 1, 1, 2, 1,
                                     1, 1, 1, 1, 1,
                                     1, 1, 1, 1, 1,
                                     1, 1, 1, 1, 1,
                                     1, 1, 1, 1, 1,
                                     1, 1, 1, 1, 1)

PONTUAÇÃO_TEMPO_DO_MARCO_JURIDICO_INSTITUCIONAL_TRATADO <- c(3, 3, 2, 2,
                                                             3, 2, 2, 2,
                                                             3, 2, 2, 2,
                                                             2, 2, 3, 3,
                                                             3, 2, 3, 1,
                                                             2, 2, 1, 2, 
                                                             2, 1, 1, 3,
                                                             2, 2, 2, 2,
                                                             1, 2, 1)

PONTUAÇÃO_DESPESAS_MILITARES_TRATADO <- c(3, 2, 3, 1, 1,
                                           2, 3, 3, 2, 1,
                                           2, 1, 2, 1, 3,
                                           1, 1, 1, 1, 1,
                                           1, 1, 1, 1, 2,
                                           2, 1, 2, 2, 1,
                                           1, 1, 1, 2, 1)

PONTUAÇÃO_SECURITIZAÇÃO_TRATADO <- c(3, 3, 1, 3, 3,
                                     2, 3, 1, 3, 3,
                                     3, 2, 2, 3, 2,
                                     1, 3, 1, 3, 3,
                                     2, 1, 2, 1, 1,
                                     2, 1, 2, 1, 2,
                                     1, 1, 1, 1, 1)

BANCO_GCI_2018 <- data.frame(PAÍS, SIGLA, RANQUE_REGIONAL, RANQUE_GLOBAL, PONTUAÇÃO_GCI, PONTUAÇÃO_GCI_TRATADO, PONTUAÇÃO_IDH, PONTUAÇÃO_IDH_TRATADO, PONTUAÇÃO_MILITARIZAÇÃO_TRATADO, PONTUAÇÃO_EVENTOS_RAROS_TRATADO, PONTUAÇÃO_TEMPO_DO_MARCO_JURIDICO_INSTITUCIONAL_TRATADO, PONTUAÇÃO_DESPESAS_MILITARES_TRATADO, PONTUAÇÃO_SECURITIZAÇÃO_TRATADO)

```

```{r}
teste_1 <- lm(PONTUAÇÃO_GCI ~ PONTUAÇÃO_DESPESAS_MILITARES_TRATADO, data = BANCO_GCI_2018)

summary(teste_1)
```
```{r}
teste_2 <- lm(PONTUAÇÃO_GCI ~ PONTUAÇÃO_SECURITIZAÇÃO_TRATADO, data = BANCO_GCI_2018)

summary(teste_2)
```

```{r}
teste_3 <- lm(PONTUAÇÃO_GCI ~ PONTUAÇÃO_TEMPO_DO_MARCO_JURIDICO_INSTITUCIONAL_TRATADO, data = BANCO_GCI_2018)

summary(teste_3)
```


```{r}
teste_4 <- lm(PONTUAÇÃO_GCI ~ PONTUAÇÃO_EVENTOS_RAROS_TRATADO, data = BANCO_GCI_2018)

summary(teste_4)
```

```{r}
teste_5 <- lm(PONTUAÇÃO_GCI ~ PONTUAÇÃO_MILITARIZAÇÃO_TRATADO, data = BANCO_GCI_2018)

summary(teste_5)
```

```{r}
teste_6 <- lm(PONTUAÇÃO_GCI ~ PONTUAÇÃO_IDH, data = BANCO_GCI_2018)

summary(teste_6)
```


```{r}
teste_7 <- lm(PONTUAÇÃO_GCI ~ PONTUAÇÃO_IDH_TRATADO, data = BANCO_GCI_2018)

summary(teste_7)
```



```{r}
library(scales)
```


```{r}
ggplot(BANCO_GCI_2018, aes(PONTUAÇÃO_TEMPO_DO_MARCO_JURIDICO_INSTITUCIONAL_TRATADO, ..count../sum(..count..) )) +
  geom_bar(na.rm = T) +
  scale_y_continuous(labels = percent) + labs(tittle = "Tempo do Marco Jurídico-Institucional - Américas",
       x = "1 = Marco Inexistente (0); 2 = Marco Recente (1); 3 = Marco antigo (2)",
       y = "Distribuição dos Casos")
```


```{r}
ggplot(BANCO_GCI_2018, aes(PONTUAÇÃO_DESPESAS_MILITARES_TRATADO, ..count../sum(..count..) )) +
  geom_bar(na.rm = T) +
  scale_y_continuous(labels = percent) + labs(tittle = "Despesas Militares - Américas",
       x = "1 = N/A ou menos de 1% do PIB (0); 2 = Entre 1% e 2% do PIB (1); 3 = Mais de 2% do PIB (2)",
       y = "Distribuição dos Casos")
```

```{r}
ggplot(BANCO_GCI_2018, aes(PONTUAÇÃO_SECURITIZAÇÃO_TRATADO, ..count../sum(..count..) )) +
  geom_bar(na.rm = T) +
  scale_y_continuous(labels = percent) + labs(tittle = "Securitização - Américas",
       x = "1 = Não Securitizado (0); 2 = Em Securitização (1); 3 = Securitizado (2)",
       y = "Distribuição dos Casos")
```

```{r}
ggplot(BANCO_GCI_2018, aes(PONTUAÇÃO_IDH_TRATADO, ..count../sum(..count..) )) +
  geom_bar(na.rm = T) +
  scale_y_continuous(labels = percent) + labs(tittle = "Índice de Desenvolvimento Humano - Américas",
       x = "0 = Baixo ou Médio; 1 = Elevado; 2 = Muito Elevado",
       y = "Distribuição dos Casos")
```

```{r}
ggplot(BANCO_GCI_2018, aes(PONTUAÇÃO_MILITARIZAÇÃO_TRATADO, ..count../sum(..count..) )) +
  geom_bar(na.rm = T) +
  scale_y_continuous(labels = percent) + labs(tittle = "Militarização - Américas",
       x = "0 = Não Militarizado; 1 = Militarizado",
       y = "Distribuição dos Casos")
```

```{r}
ggplot(BANCO_GCI_2018, aes(PONTUAÇÃO_EVENTOS_RAROS_TRATADO, ..count../sum(..count..) )) +
  geom_bar(na.rm = T) +
  scale_y_continuous(labels = percent) + labs(tittle = "Eventos Raros - Américas",
       x = "1 = Ausência de Eventos Raros (0); 2 = Evento Isolado (1); 3 = Presença de Eventos Raros (2)",
       y = "Distribuição dos Casos")
```

```{r}
library(QCApro)
help("QCApro")
```

```{r}
tabela_verdade <- truthTable(BANCO_GCI_2018, outcome = "PONTUAÇÃO_GCI_TRATADO", neg.out = FALSE, exo.facs = c("PONTUAÇÃO_IDH_TRATADO", "PONTUAÇÃO_MILITARIZAÇÃO_TRATADO", "PONTUAÇÃO_EVENTOS_RAROS_TRATADO", "PONTUAÇÃO_TEMPO_DO_MARCO_JURIDICO_INSTITUCIONAL_TRATADO", "PONTUAÇÃO_DESPESAS_MILITARES_TRATADO", "PONTUAÇÃO_SECURITIZAÇÃO_TRATADO"),
           n.cut = 1, incl.cut1 = 1, incl.cut0 = 1, complete = FALSE, 
           show.cases = FALSE, decreasing = TRUE, 
           inf.test = c("binom"), use.letters = FALSE)

print(tabela_verdade)
```




















```{r}
ggplot(BANCO_GCI_2018, aes(PONTUAÇÃO_GCI, ..count../sum(..count..) )) +
  geom_bar(na.rm = T) +
  scale_y_continuous(labels = percent)
```

```{r}
cor.test(BANCO_GCI_2018$PONTUAÇÃO_GCI, BANCO_GCI_2018$PONTUAÇÃO_IDH)
```

```{r}
ggplot(BANCO_GCI_2018, aes(PONTUAÇÃO_GCI, PONTUAÇÃO_IDH)) +
geom_jitter() + 
  labs(x = "GCI",
y = "IDH")

```
